require("plugins.plugin-pack")
require("plugins.lsp")
require("plugins.vim-airline-themes")
require("plugins.telescope")
require("plugins.gitsigns")
require("plugins.dashboard-nvim")
require("plugins.vim-commentary")
require("plugins.nvim-tree")
